<?php $title = 'Revision History: ' . $entity; ?>
<?= $this->partial('partial/admin-assets'); ?>
<?php $this->navigation('navigation')
    ->findOneBy('admin', get_class($entity))
    ->addPage([
        'label'  => 'History',
        'uri'    => '#',
        'active' => true,
        'class'  => 'hidden-nav',
    ]); ?>
<?php $this->headTitle($title); ?>

<h2 class="page-header"><?= $title ?></h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 10%">Version</th>
                <th style="width: 10%">Action</th>
                <th style="width: 15%">Timestamp</th>
                <th>Data</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php if (!count($result)) : ?>
                <tr>
                    <td colspan="5" class="text-center">There are no actions to display.</td>
                </tr>
            <?php else : ?>
                <?php $currentVersion = true; ?>
                <?php foreach ($result as $logEntry) : ?>
                    <tr>
                        <td><?= $logEntry->getVersion() ?></td>
                        <td><?= ucfirst($logEntry->getAction()) ?></td>
                        <td><?= $logEntry->getLoggedAt()->format('Y-m-d H:i:s') ?></td>
                        <td>
                            <?php foreach ($logEntry->getData() as $key => $value): ?>
                            <?php if ($value !== null || $logEntry->getAction() == 'update'): ?>
                            <div>Set <b><?= $key ?></b> to <code><?= ($value === null ? 'NULL' : (is_array($value) ? reset($value) : $value)) ?></code></div>
                            <?php endif; ?>
                            <?php endforeach; ?>
                        </td>
                        <td class="text-right">
                            <?php if ($currentVersion) : ?>
                                <a class="btn btn-default btn-sm disabled"><span class="fas fa-undo" aria-hidden="true"></span> Rollback</a>
                            <?php else : ?>
                                <a class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalForm" href="<?= $this->url(null, ['action' => 'revert', 'id' => $entity->getId(), 'version' => $logEntry->getVersion()], true) ?>">
                                    <span class="fas fa-undo" aria-hidden="true"></span> Rollback
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php $currentVersion = false; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>

<div class="modal" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="modalFormLabel" aria-hidden="true"></div>