<?php $title = 'Admin Dashboard'; ?>
<?= $this->partial('partial/admin-assets'); ?>
<?php $this->headTitle($title); ?>

<h2 class="page-header"><?php echo $title; ?></h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Entity</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!count($result)): ?>
            <tr>
                <td class="text-center">There are no entities to display.</td>
            </tr>
        <?php else: ?>
            <?php foreach ($result as $entitySlug => $pluralName): ?>
            <tr>
                <td><a href="<?php echo $this->url('ace-admin/entity', ['action' => 'list', 'entity' => $entitySlug], true); ?>"><?php echo $pluralName; ?></a></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>
