<?php $title = 'Manage ' . $plural; ?>
<?= $this->partial('partial/admin-assets'); ?>
<?php $this->headTitle($title); ?>

<div class="admin-header">
    <?= $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE) ?>
    <a class="btn btn-success pull-right" data-toggle="modal" data-target="#modalForm" data-remote="false" href="<?= $this->url(null, ['action' => 'add'], true) ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add <?= $singular ?>
    </a>
</div>

<h2 class="page-header"><?= $title ?></h2>

<?php if ($search): ?>
    <h5>
        Search results for
        <a class="label label-default" href="<?= $this->url(null, [], ['query' => ['page' => $page, 'sort' => $sort]], true) ?>">
            <?= $search ?> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </a>
    </h5>
<?php endif; ?>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
                <?php if ($column['sortName']): ?>
                    <th><?= $this->sortControl($sort, $column['sortName'], $column['label'], $column['sortReverse'], ['q' => $search, 'page' => $page]) ?></th>
                <?php else: ?>
                    <th><?= $column['label'] ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (!count($result)): ?>
            <tr>
                <td colspan="<?= count($columns)+1 ?>" class="text-center">There are no <?= strtolower($plural) ?> to display.</td>
            </tr>
        <?php else: ?>
            <?php foreach ($result as $entity): ?>
                <tr>
                    <?php foreach ($columns as $column): ?>
                        <?php $method = $column['method']; ?>
                        <?php $value = $entity->$method(); ?>
                        <?php if (is_bool($value) && $value): ?>
                            <td class="text-center"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></td>
                        <?php else: ?>
                            <td><?= $value ?></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <td class="text-right">
                        <?php if ($hasLog): ?>
                        <a class="btn btn-success btn-sm" href="<?= $this->url(null, ['action' => 'history', 'id' => $entity->getId()], true) ?>">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span> History
                        </a>
                        <?php endif; ?>
                        <a class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modalForm" data-remote="false" href="<?= $this->url(null, ['action' => 'edit', 'id' => $entity->getId()], true) ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        <a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalForm" data-remote="false" href="<?= $this->url(null, ['action' => 'delete', 'id' => $entity->getId()], true) ?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>

<?php if (count($result)): ?>
    <?= $this->paginationControl($result, 'sliding', 'partial/datagrid-paginator.phtml', ['query' => ['q' => $search, 'page' => $page, 'sort' => $sort]]) ?>
<?php endif; ?>

<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="modalFormLabel" aria-hidden="true"></div>