<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="modalFormLabel"><?= $this->headTitle()->renderTitle() ?></h4>
        </div>
        <div class="modal-body">
            <?= $this->content ?>
        </div>
    </div>
</div>